//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldType
    {
        public FieldType()
        {
            this.tblFldDets = new HashSet<FieldDetail>();
        }
    
        public short FldTyp { get; set; }
        public string FldTypDesc { get; set; }
    
        public virtual ICollection<FieldDetail> tblFldDets { get; set; }
    }
}
