//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexField
    {
        public string TblId { get; set; }
        public string IdxId { get; set; }
        public short IdxPos { get; set; }
        public string FldAlias { get; set; }
        public string SortOrdr { get; set; }
    
        public virtual IndexHeader tblIdxHdr { get; set; }
    }
}
