//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceTable
    {
        public SourceTable()
        {
            this.Samples = new HashSet<Sample>();
            this.TableJoins = new HashSet<TableJoin>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string SourceTableName { get; set; }
        public bool IsE1 { get; set; }
        public int ConvTableSource_ConvTable { get; set; }
        public Nullable<bool> PrimarySource { get; set; }
    
        public virtual ICollection<Sample> Samples { get; set; }
        public virtual Table Table { get; set; }
        public virtual ICollection<TableJoin> TableJoins { get; set; }
        public virtual TableHeader TableHeader { get; set; }
    }
}
