//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Samples = new HashSet<Sample>();
            this.SourceTables = new HashSet<SourceTable>();
            this.SampleTemplates = new HashSet<SampleTemplate>();
            this.UserSampleTemplates = new HashSet<UserSampleTemplate>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string TableName { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string Notes { get; set; }
        public bool HasConversionDoc { get; set; }
        public byte[] IssueScreenshot { get; set; }
        public bool UseSampleData { get; set; }
        public int Table_Conversion { get; set; }
        public Nullable<bool> GetSampleDatafromE1 { get; set; }
    
        public virtual Conversion Conversion { get; set; }
        public virtual ICollection<Sample> Samples { get; set; }
        public virtual ICollection<SourceTable> SourceTables { get; set; }
        public virtual ICollection<SampleTemplate> SampleTemplates { get; set; }
        public virtual ICollection<UserSampleTemplate> UserSampleTemplates { get; set; }
    }
}
