//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableHeader
    {
        public TableHeader()
        {
            this.IndexHeaders = new HashSet<IndexHeader>();
            this.TableFields = new HashSet<TableField>();
            this.SourceTable = new HashSet<SourceTable>();
        }
    
        public string TableName { get; set; }
        public string TblDesc { get; set; }
        public string FieldPrefix { get; set; }
        public string TblSy { get; set; }
        public string TblSyr { get; set; }
        public string TblDATP { get; set; }
    
        public virtual ICollection<IndexHeader> IndexHeaders { get; set; }
        public virtual ICollection<TableField> TableFields { get; set; }
        public virtual ICollection<SourceTable> SourceTable { get; set; }
    }
}
