//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableField
    {
        public TableField()
        {
            this.TableJoins = new HashSet<TableJoin>();
            this.TableJoins1 = new HashSet<TableJoin>();
        }
    
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<short> Position { get; set; }
        public string IndexType { get; set; }
    
        public virtual FieldDetail FieldDetails { get; set; }
        public virtual TableHeader TableHeader { get; set; }
        public virtual ICollection<TableJoin> TableJoins { get; set; }
        public virtual ICollection<TableJoin> TableJoins1 { get; set; }
    }
}
