//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableJoin
    {
        public TableJoin()
        {
            this.SampleValues = new HashSet<SampleValue>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string SourceFieldName { get; set; }
        public string ConvFieldName { get; set; }
        public string SourceTableName { get; set; }
        public string ConvTableName { get; set; }
        public int TableJoins_SourceTables { get; set; }
    
        public virtual SourceTable SourceTable { get; set; }
        public virtual TableField ConversionField { get; set; }
        public virtual TableField SourceField { get; set; }
        public virtual ICollection<SampleValue> SampleValues { get; set; }
    }
}
