//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJonOpr
    {
        public tblJonOpr()
        {
            this.tblVewJons = new HashSet<tblVewJon>();
        }
    
        public string JoinOperator { get; set; }
        public string OperatorDisplay { get; set; }
    
        public virtual ICollection<tblVewJon> tblVewJons { get; set; }
    }
}
