//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Validation.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XRef
    {
        public string WorldValue { get; set; }
        public string E1Value { get; set; }
        public string FieldType { get; set; }
        public int Id { get; set; }
        public string TableName { get; set; }
    }
}
